# Generated by Django 3.2.2 on 2021-05-23 00:29

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='athlete',
            options={'verbose_name': 'Sporcu', 'verbose_name_plural': 'Sporcular'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategori', 'verbose_name_plural': 'Kategoriler'},
        ),
        migrations.AlterModelOptions(
            name='controlpoint',
            options={'verbose_name': 'Kontrol Noktası', 'verbose_name_plural': 'Kontrol Noktaları'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Etkinlik', 'verbose_name_plural': 'Etkinlikler'},
        ),
        migrations.AlterModelOptions(
            name='record',
            options={'verbose_name': 'Kayıt', 'verbose_name_plural': 'Kayıtlar'},
        ),
        migrations.AlterField(
            model_name='athlete',
            name='card_id',
            field=models.IntegerField(verbose_name='Kart NO'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category', verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ad Soyad'),
        ),
        migrations.AlterField(
            model_name='category',
            name='control_points',
            field=models.JSONField(default=list, validators=[api.models.validate_control_points], verbose_name='Kontrol Noktaları'),
        ),
        migrations.AlterField(
            model_name='category',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.event', verbose_name='Etkinlik'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Kategori Adı'),
        ),
        migrations.AlterField(
            model_name='controlpoint',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='controlpoint',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Adı'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(unique=True, verbose_name='Tarih'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Etkinlik Adı'),
        ),
        migrations.AlterField(
            model_name='record',
            name='athlete',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.athlete', verbose_name='Sporcu'),
        ),
        migrations.AlterField(
            model_name='record',
            name='results',
            field=models.JSONField(default=list, verbose_name='Sonuçlar'),
        ),
        migrations.AlterUniqueTogether(
            name='athlete',
            unique_together={('category', 'card_id')},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('event', 'name'), ('event', 'control_points')},
        ),
    ]
